### ISSUE TITLE
changed favicon.ico does not show in site

### ISSUE THREAD

**Issue by peterennis** [docascode/docfx-seed#10]
![capture43](https://cloud.githubusercontent.com/assets/140737/16898114/6942b1aa-4b7e-11e6-92a2-71b507b714ca.PNG)

**Comment by hellosnow** [comment]
Hi, did you change the icon directly in _site folder? I tried this way and seems working well, both in chrome and IE. Would you like to provide more detailed steps to repro this issue?

![image](https://cloud.githubusercontent.com/assets/1836885/16905899/2ea4807e-4ce0-11e6-8e48-4499882d3eb7.png)

**Comment by peterennis** [comment]
That worked. Thanks!
