### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by peterennis** [docascode/docfx-seed#12]
Fussy! It does not like a trailing backslash.
![capture48](https://cloud.githubusercontent.com/assets/140737/16933088/a213cdb6-4cff-11e6-817a-bc6093fb5bf0.PNG)

**Comment by superyyrrzz** [comment]
Seems it treats `\"` as a `"` character, so the path becomes a unclosed string. The following 2 forms can work for you: `--output c:\themes\` or `--output "c:\\themes\\"`

**Comment by superyyrrzz** [comment]
BTW, For DocFX related issues, you can open on DocFX's repo: https://github.com/dotnet/docfx/issues

**Comment by peterennis** [comment]
Do you want me to open a ticket for this on the docfx repo instead?

**Comment by superyyrrzz** [comment]
I think this one can remain here. You can move to DocFX repo if having other issues.

**Comment by peterennis** [comment]
Re: https://github.com/docascode/docfx-seed/issues/12#issuecomment-233517951
The solution that worked for me was not to use the final backslash.
