### ISSUE TITLE
Overwrite for REST API doesn't work with markdown engine 'markdig'

### ISSUE THREAD

**Issue by patricksadowski** [docascode/docfx-seed#25]
The content of `specs/petstore-operations.md` is not fully applied to the resulting site during build.

![image](https://user-images.githubusercontent.com/9739149/39745319-33307a16-52a7-11e8-89c3-9e0ef251de8d.png)

Steps to reproduce:
*  Download and install docfx 2.35.4.0
*  Clone this repo
*  Add `"markdownEngineName": "markdig"` to `docfx.json` because it's the default engine like mentioned [here](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html) in the note section
*  Build the documentation
*  Open the documentation and navigate to `REST API` in the top bar

Everything is fine without the explicit markdown engine setting.

**Comment by qinezh** [comment]
Thanks for reporting this issue. Currently markdig engine doesn't support multiple YAML headers inside a markdown. So the solution for overwrite markdown with multiple YAML header is to split it into several files.

Here's the commit to do it for docfx-seed: https://github.com/docascode/docfx-seed/commit/0c958fcbc013c0c72001465a6fb449115dc9ac28
