### ISSUE TITLE
How to set docfx.json file and connect with swagger.json on live server

### ISSUE THREAD

**Issue by uthens** [docascode/docfx-seed#28]
Hi, 

Now it's worked on local file i save file from debug mode, But i want to know how to link with web api online ? 

**sample..**
I run debug on vs2019
http://localhost:5200/xxxapi/swagger/v1/swagger.json

![Annotation 2019-08-21 180200](https://user-images.githubusercontent.com/10783170/63426901-1f150b00-c43e-11e9-8343-d3abac692fb0.png)

![Annotation 2019-08-21 181218](https://user-images.githubusercontent.com/10783170/63427526-88e1e480-c43f-11e9-8038-e8d4362a2a86.png)

![Annotation 2019-08-21 181354](https://user-images.githubusercontent.com/10783170/63427542-9008f280-c43f-11e9-8ec8-f1bb5afbd0ab.png)

**Comment by superyyrrzz** [comment]
track in https://github.com/dotnet/docfx/issues/5012

**Comment by uthens** [comment]
thank you for update.
